services:
  app:
    image: bricker/app
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine3.21
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
